fix(docs): Run npm install on docs.init
Fix error in pipeline due to missing node packages, such as

```
Error: Error building site: POSTCSS: failed to transform "scss/docs.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
```

Signed-off-by: Maximilian Blatt <maximilian.blatt-extern@deutschebahn.com>
(external expert on behalf of DB Netz AG)